import { Identifier, CodeableConcept, unsignedInt, Reference, Quantity, Period, BackboneElement } from "./_basic-types"
import { DomainResource } from "./_resource.types"
import { Device } from "./device"
import { Medication } from "./medication.types"
import { Organization } from "./organization.types"
import { Patient } from "./patient.types"
import { Practitioner } from "./practitioner"
import { PractitionerRole } from "./practitioner-role"
import { RelatedPerson } from "./related-person"
import { Substance } from "./substance.types"

// https://hl7.org/fhir/R4/group.html
// Generated by ChatGTP
export type Group = DomainResource & {
    resourceType: "Group",
    identifier?: Identifier[],
    active?: boolean,
    type: "person" | "animal" | "practitioner" | "device" | "medication" | "substance",
    actual: boolean,
    code?: CodeableConcept,
    name?: string,
    quantity?: unsignedInt,
    managingEntity?: Reference<Organization | RelatedPerson | Practitioner | PractitionerRole>,
    characteristic?: (BackboneElement & {
      code: CodeableConcept,
      valueCodeableConcept?: CodeableConcept,
      valueBoolean?: boolean,
      valueQuantity?: Quantity,
      valueRange?: Range,
      valueReference?: Reference<any>,
      exclude: boolean,
      period?: Period
    })[],
    member?: (BackboneElement & {
      entity: Reference<Patient | RelatedPerson | Practitioner | PractitionerRole | Device | Medication | Substance | Group>,
      period?: Period,
      inactive?: boolean
    })[]
}