import { Identifier, Reference, CodeableConcept, Quantity, Ratio, Range, dateTime, Period, Timing, Annotation, canonical, uri } from "./_basic-types";
import { DomainResource } from "./_resource.types";

export type ServiceRequest = DomainResource & {
    resourceType: "ServiceRequest",
    identifier?: Identifier[],
    instantiatesCanonical?: canonical[],
    instantiatesUri?: uri[],
    basedOn?: Reference[],
    replaces?: Reference[],
    requisition?: Identifier,
    status: "draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown",
    intent: "proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option",
    category?: CodeableConcept[],
    priority?: "routine" | "urgent" | "asap" | "stat",
    doNotPerform?: boolean,
    code?: CodeableConcept,
    orderDetail?: CodeableConcept[],
    quantityQuantity?: Quantity,
    quantityRatio?: Ratio,
    quantityRange?: Range,
    subject: Reference,
    encounter?: Reference,
    occurrenceDateTime?: dateTime,
    occurrencePeriod?: Period,
    occurrenceTiming?: Timing,
    asNeededBoolean?: boolean,
    asNeededCodeableConcept?: CodeableConcept,
    authoredOn?: dateTime,
    requester?: Reference,
    performerType?: CodeableConcept,
    performer?: Reference[],
    locationCode?: CodeableConcept[],
    locationReference?: Reference[],
    reasonCode?: CodeableConcept[],
    reasonReference?: Reference[],
    insurance?: Reference[],
    supportingInfo?: Reference[],
    specimen?: Reference[],
    bodySite?: CodeableConcept[],
    note?: Annotation[],
    patientInstruction?: string,
    relevantHistory?: Reference[]
};